### PR TITLE
Ilya Doroshenko laba 1

### PR DESCRIPTION
**Pull request by iddoroshenko**

### CODE REVIEW

**Comment by geexie** [comment]
@iddoroshenko, in general look good. Could you please give your pass some unique name, for example by your nickname and place to a new folder so it won't be any merge conflict and confusion later.

**Comment by iddoroshenko** [comment]
I tried to move my pass to a new folder, but I got an error.
I got this error by following this documentation https://llvm.org/docs/CMake.html#developing-llvm-passes-out-of-source

../../lib/libLLVMPasses.a(PassBuilder.cpp.o): In function llvm::detail::PassModel<llvm::Function, llvm::DoroshenkoPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)':
### **~/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:85: undefined reference to llvm::DoroshenkoPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)'**
collect2: error: ld returned 1 exit status
tools/lto/CMakeFiles/LTO.dir/build.make:169: recipe for target 'lib/libLTO.so.13git' failed
make[2]:  [lib/libLTO.so.13git] Error 1
CMakeFiles/Makefile2:18821: recipe for target 'tools/lto/CMakeFiles/LTO.dir/all' failed
make[1]:  [tools/lto/CMakeFiles/LTO.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by geexie** [comment]
this instruction is not quite relevant to what we are doing. We are building **in source** while instructions is about building pass outside the source tree. BTW, it uses old pass manager, so not recommended.

Most likely you forgot to add your folder to `llvm/lib/Transforms/CMakeLists.txt` so it's not build and there is nothing to link against

**Comment by iddoroshenko** [comment]
It is still not working. But I updated MR with the try to make the pass in a new directory
Could you check what I may have forgotten to do?

**Comment by geexie** [comment]
Please also add you library to the dependency of target `LLVMPasses` in `llvm/lib/Passes/CMakeLists.txt`

**Comment by iddoroshenko** [comment]
Now it works, thanks

**Pull request merged**
