### PR TITLE
Dmitry sazanov lab1

### PR DESCRIPTION
**Pull request by dlots**
Build successful

### CODE REVIEW

**Comment by geexie** [comment]
@dlots, I cannot accept your lab work since it's PRed after due date

**Comment by dlots** [comment]
> @dlots, I cannot accept your lab work since it's PRed after due date

But my first pull request was published in time. I had to close it and create this one because of build issues. The algorithm is the same, there are just a few corrections made to syntax. Could you please reconsider? The link to the old pull request: https://github.com/geexie/llvm-project/pull/26

**Comment by geexie** [comment]
@dlots, OK. got you. You should have mentioned the old one in description...

**Comment by dlots** [comment]
@geexie, my bad, I'll be more careful in future. Thanks a lot!

**Pull request merged**
