### PR TITLE
Voronova_Anastasia_lab3

### PR DESCRIPTION
**Pull request by VoronovaAnastasia**

### CODE REVIEW

**Review by geexie — CHANGES_REQUESTED** [review]
@VoronovaAnastasia, please resolve merge conflicts and keep your second lab as well

**Comment by VoronovaAnastasia** [comment]
I tried to delete this commit and push everything again. But I have the error  when create "push origin"   "error: failed to push some refs to 'https://github.com/VoronovaAnastasia/llvm-project.git'" . It recommends to do git pull, but after that nothing changed. I do not know how to solve this problem. Can you recommend, what to do?

**Comment by geexie** [comment]
You might need to try `git push -f`

**Comment by VoronovaAnastasia** [comment]
@geexie , I resolved conflicts, everything you can find in new pull request. Can I close this?

**Comment by geexie** [comment]
@VoronovaAnastasia, ok

**Pull request closed without merging**
