### PR TITLE
Audachina lab4

### PR DESCRIPTION
**Pull request by anastasiaudachina**

### CODE REVIEW

**Review by geexie — CHANGES_REQUESTED** [review]
@anastasiaudachina, your code cannot be built

**Review by geexie — CHANGES_REQUESTED** [review]
@anastasiaudachina, I still cannot build your code

**Comment by anastasiaudachina** [comment]
@geexie I can’t understand where is mistake :c on my laptop I have no problems, my code is being built successfully

**Comment by geexie** [comment]
```
[100%] Building CXX object examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/ast.cpp.o
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/lexer.cpp:3:6: error: no type named 'string' in
      namespace 'std'
std::string Lexer::getToken() {
~~~~~^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/lexer.cpp:3:13: error: use of undeclared
      identifier 'Lexer'
std::string Lexer::getToken() {
            ^
2 errors generated.
make[3]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/lexer.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from In file included from /Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:1:
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:41:2: error: expected/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:1:
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:41:2: error: expected ';' after class
 ';'}
 ^
 ;
 /Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:51:2: error: expected ';' after class
}
 ^
 ;
after class
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:}
 ^
 ;
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:51:2: error: expected ';' after class
}
 ^
 ;
60/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:60:2: error: expected :2: error: expected ';' after class
}
 ^
';' after class
}
 ^
 ;
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:4:28: error: member 'VariableExpr' has
      the same name as its class
llvm::Value* VariableExpr::VariableExpr = NULL;
                           ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:4:28: error: no member named
      'VariableExpr' in 'VariableExpr'
llvm::Value* VariableExpr::VariableExpr = NULL;
             ~~~~~~~~~~~~~~^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:15:16: error: use of undeclared
      identifier 'module'
  auto power = module->getOrInsertFunction("pow", fTy);
               ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:34:36: error: qualified reference to
      'VariableExpr' is a constructor name rather than a type in this context
  llvm::Value* var = VariableExpr::VariableExpr;
                                   ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.cpp:34:48: error: expected '(' for
      function-style cast or type construction
  llvm::Value* var = VariableExpr::VariableExpr;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:22:19: error: redefinition of 'fOp'
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:17:19: note: previous definition is
      here
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:23:19: error: redefinition of 'sOp'
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:18:19: note: previous definition is
      here
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:27:19: error: redefinition of 'fOp'
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:17:19: note: previous definition is
      here
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:28:19: error: redefinition of 'sOp'
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:18:19: note: previous definition is
      here
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:29:24: error: calling a private
      constructor of class 'PowerExpr'
            return new PowerExpr(fOp, sOp);
                       ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:54:3: note: implicitly declared private
      here
  PowerExpr(Expr* fArg, Expr* sArg) : fOp(fArg), sOp(sArg) {}
  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:31:9: error: cannot jump from switch
      statement to this case label
        default:
        ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:18:19: note: jump bypasses variable
      initialization
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:17:19: note: jump bypasses variable
      initialization
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:26:9: error: cannot jump from switch
      statement to this case label
        case '^':
        ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:18:19: note: jump bypasses variable
      initialization
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:17:19: note: jump bypasses variable
      initialization
            Expr* fOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:21:9: error: cannot jump from switch
      statement to this case label
        case '*':
        ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:18:19: note: jump bypasses variable
      initialization
            Expr* sOp = parseExpr();
                  ^
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/parser.cpp:17:19: note: jump bypasses variable
      initialization
            Expr* fOp = parseExpr();
                  ^
8 errors generated.
make[3]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/ast.cpp.o] Error 1
In file included from /Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/audachinaLambda.cpp:1:
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:41:2: error: expected ';' after class
}
 ^
 ;
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:51:2: error: expected ';' after class
}
 ^
 ;
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/ast.hpp:60:2: error: expected ';' after class
}
 ^
 ;
11 errors generated.
make[3]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/parser.cpp.o] Error 1
/Users/mkolpako/code/llvm-project/llvm/examples/audachinaLambda/audachinaLambda.cpp:44:3: error: use of
      undeclared identifier 'VarExpr'
  VarExpr::varValue = argX;
  ^
4 errors generated.
make[3]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/audachinaLambda.cpp.o] Error 1
make[2]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/all] Error 2
make[1]: *** [examples/audachinaLambda/CMakeFiles/audachinaLambda.dir/rule] Error 2
make: *** [audachinaLambda] Error 2

**Pull request closed without merging**
